vault:
  path: "ROOT_DIRECTORY_PATH/dev"
  capture_dir: "capture/raw_capture"
  media_dir: "capture/raw_capture/media"

database:
  path: "dev/main.db"

ui:
  clipboard_poll_ms: 200
  use_modality_icons: true

theme:
  mode: "dark"
  accent_color: "#4c1d95"
  accent_hover: "#3730a3"
  accent_shadow: "rgba(76, 29, 149, 0.2)"
  background_color: "#1f2937"
  text_color: "#f9fafb"
  input_background: "#374151"
  input_border: "#4b5563"

capture:
  auto_detect_modalities: true
  context_suggestions: true
  tag_suggestions: true
  sources_suggestions: true
  geolocation_enabled: true
  max_content_length: 10000

development:
  debug_logging: true
  test_mode: true
  mode: "dev"
