
vault:
  path: "~/notes"
  capture_dir: "capture/raw_capture"
  media_dir: "capture/raw_capture/media"

ui:
  clipboard_poll_ms: 200

capture:
  auto_detect_modalities: true
  context_suggestions: true
  tag_suggestions: true
  sources_suggestions: true
  geolocation_enabled: true
  default_importance: 0.5
  max_content_length: 10000

development:
  debug_logging: false
  test_mode: false
