
vault:
  path: "~/notes"
  capture_dir: "capture/raw_capture"
  media_dir: "capture/raw_capture/media"

vault_dev:
  path: "ROOT_DIRECTORY_PATH"
  capture_dir: "raw_capture"
  media_dir: "raw_capture/media"

ui:
  clipboard_poll_ms: 200
  use_modality_icons: false

theme:
  accent_color: "#4c1d95"
  accent_hover: "#3730a3"
  accent_shadow: "rgba(76, 29, 149, 0.2)"

capture:
  auto_detect_modalities: true
  context_suggestions: true
  tag_suggestions: true
  sources_suggestions: true
  geolocation_enabled: true
  max_content_length: 10000

development:
  debug_logging: false
  test_mode: false
